:mod:`fldatamigration.fl.datamigration.exceptions.invalid_exception`
====================================================================

.. py:module:: fldatamigration.fl.datamigration.exceptions.invalid_exception


Module Contents
---------------

.. py:exception:: InvalidException(*args)

   Bases: :class:`Exception`

   .. method:: __str__(self)




