:mod:`rec_to_nwb.processing.exceptions.different_number_of_tasks_and_epochs_exception`
======================================================================================

.. py:module:: rec_to_nwb.processing.exceptions.different_number_of_tasks_and_epochs_exception


Module Contents
---------------

.. py:exception:: DifferentNumberOfTasksAndEpochsException

   Bases: :class:`Exception`


